### GET all contacts
GET http://localhost:3000/api/contacts

### GET a single contact by ID
GET http://localhost:3000/api/contacts/{{contactId}}

### POST create a new contact
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "firstName": "Marcos",
  "lastName": "Campos",
  "email": "marcos@example.com",
  "favoriteColor": "blue",
  "birthday": "1990-01-01"
}

### PUT update a contact
PUT http://localhost:3000/api/contacts/{{contactId}}
Content-Type: application/json

{
  "firstName": "Updated Name"
}

### DELETE a contact
DELETE http://localhost:3000/api/contacts/{{contactId}}
